// 반복 작업 스케줄 규칙 + 규칙에 따른 작업 자동 생성.
import {
  addDays,
  differenceInCalendarDays,
  formatISO,
  getISODay,
  isAfter,
  isBefore,
  lastDayOfMonth,
  parseISO,
} from 'date-fns'
import { uuid } from '../../utils/uuid.js'
import { normalizeRule, normalizeScheduleSettings } from './normalize.js'

function monthsDiff(fromDate, toDate) {
  return (toDate.getFullYear() - fromDate.getFullYear()) * 12 + (toDate.getMonth() - fromDate.getMonth())
}

function matchRuleOnDate(rule, date) {
  const start = parseISO(rule.startDate)
  if (isBefore(date, start)) {
    return false
  }

  if (rule.endDate) {
    const end = parseISO(rule.endDate)
    if (isAfter(date, end)) {
      return false
    }
  }

  const interval = Math.max(1, Number(rule.interval || 1))
  const dayDiff = differenceInCalendarDays(date, start)

  if (rule.frequency === '매일') {
    return dayDiff % interval === 0
  }

  if (rule.frequency === '매주') {
    const weekday = Number(rule.dayOfWeek || getISODay(start))
    if (getISODay(date) !== weekday) {
      return false
    }

    return Math.floor(dayDiff / 7) % interval === 0
  }

  const monthDelta = monthsDiff(start, date)
  if (monthDelta < 0 || monthDelta % interval !== 0) {
    return false
  }

  const requestedDay = Number(rule.dayOfMonth || start.getDate())
  const clampedDay = Math.min(requestedDay, lastDayOfMonth(date).getDate())
  return date.getDate() === clampedDay
}

export function toKey(dateString) {
  const date = parseISO(dateString)
  return formatISO(date, { representation: 'date' })
}

export function createSchedulerActions(ctx) {
  const { state, persistAll, logChange } = ctx

  async function upsertScheduleRule(payload) {
    const normalized = normalizeRule(payload)
    const index = state.value.scheduleRules.findIndex((item) => item.id === normalized.id)

    if (index >= 0) {
      state.value.scheduleRules[index] = {
        ...state.value.scheduleRules[index],
        ...normalized,
      }
    } else {
      state.value.scheduleRules.push({
        ...normalized,
        id: normalized.id || uuid(),
      })
    }

    await persistAll()
  }

  async function removeScheduleRule(id) {
    state.value.scheduleRules = state.value.scheduleRules.filter((rule) => rule.id !== id)
    await persistAll()
  }

  async function updateScheduleSettings(payload) {
    state.value.scheduleSettings = normalizeScheduleSettings({
      ...state.value.scheduleSettings,
      ...payload,
    })
    await persistAll()
  }

  function isDuplicateTask(normalizedRule, dueDate, duplicatePolicy) {
    if (duplicatePolicy === 'allow') {
      return false
    }

    if (duplicatePolicy === 'title-and-date') {
      return state.value.tasks.some(
        (task) =>
          task.title === normalizedRule.title &&
          task.dueDate === dueDate,
      )
    }

    return state.value.tasks.some(
      (task) => task.scheduleRuleId === normalizedRule.id && task.dueDate === dueDate,
    )
  }

  async function runTaskScheduler({ daysAhead, duplicatePolicy, persist = true } = {}) {
    const resolvedDays = Math.max(1, Number(daysAhead || state.value.scheduleSettings.generationDays || 21))
    const resolvedPolicy = duplicatePolicy || state.value.scheduleSettings.duplicatePolicy || 'rule-and-date'
    const todayDate = new Date()
    const endDate = addDays(todayDate, resolvedDays)
    const generatedTasks = []

    for (const rule of state.value.scheduleRules) {
      const normalizedRule = normalizeRule(rule)
      if (!normalizedRule.enabled || !normalizedRule.startDate) {
        continue
      }

      for (let cursor = new Date(todayDate); cursor <= endDate; cursor = addDays(cursor, 1)) {
        if (!matchRuleOnDate(normalizedRule, cursor)) {
          continue
        }

        const dueDate = formatISO(cursor, { representation: 'date' })
        const alreadyExists = isDuplicateTask(normalizedRule, dueDate, resolvedPolicy)

        if (alreadyExists) {
          continue
        }

        generatedTasks.push({
          id: uuid(),
          title: normalizedRule.title,
          dueDate,
          frequency: normalizedRule.frequency,
          category: normalizedRule.category,
          status: '예정',
          progress: 0,
          logs: [{ date: new Date().toISOString(), note: '스케줄 규칙에 의해 자동 생성.' }],
          autoGenerated: true,
          scheduleRuleId: normalizedRule.id,
        })
      }
    }

    if (generatedTasks.length) {
      state.value.tasks.push(...generatedTasks)
      logChange('작업', `자동 생성 작업 ${generatedTasks.length}건`, 'add')
      if (persist) {
        await persistAll()
      }
    }

    return generatedTasks.length
  }

  async function deduplicateTasks() {
    const seen = new Set()
    const before = state.value.tasks.length
    state.value.tasks = state.value.tasks.filter((task) => {
      const key = `${task.title}|${task.dueDate}`
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    await persistAll()
    return before - state.value.tasks.length
  }

  return {
    upsertScheduleRule,
    removeScheduleRule,
    updateScheduleSettings,
    runTaskScheduler,
    deduplicateTasks,
  }
}
