// 작업 CRUD + 진행기록 CRUD + 알림/템플릿/예정 목록 + 전체 초기화.
import { addDays, formatISO, parseISO } from 'date-fns'
import { uuid } from '../../utils/uuid.js'
import { diffFields, formatFieldDiff, snapshotForRevert, truncateForLog } from '../../utils/changeLogUtils.js'
import { toKey } from './scheduler.js'

export function createTaskActions(ctx) {
  const { state, persistAll, logChange } = ctx

  async function upsertTask(payload) {
    const index = state.value.tasks.findIndex((item) => item.id === payload.id)

    if (index >= 0) {
      const before = { ...state.value.tasks[index] }
      state.value.tasks[index] = {
        ...state.value.tasks[index],
        ...payload,
      }
      const fields = diffFields(before, state.value.tasks[index], {
        title: '제목',
        dueDate: '기한',
        frequency: '주기',
        category: '분류',
        priority: '우선순위',
        status: '상태',
        progress: '진행률',
        notes: '메모',
      })
      logChange('작업', state.value.tasks[index].title, 'update', formatFieldDiff(fields), { refId: payload.id, fields })
    } else {
      const dupKey = `${payload.title}|${payload.dueDate}`
      const alreadyExists = state.value.tasks.some(
        (t) => `${t.title}|${t.dueDate}` === dupKey,
      )
      if (!alreadyExists) {
        const created = {
          ...payload,
          id: payload.id || uuid(),
          logs: Array.isArray(payload.logs) ? payload.logs : [],
          status: payload.status || '예정',
          progress: Number(payload.progress || 0),
          autoGenerated: payload.autoGenerated === true,
          scheduleRuleId: payload.scheduleRuleId || null,
        }
        state.value.tasks.push(created)
        logChange('작업', created.title, 'add')
      }
    }

    await persistAll()
  }

  async function removeTask(id) {
    const target = state.value.tasks.find((item) => item.id === id)
    state.value.tasks = state.value.tasks.filter((item) => item.id !== id)
    if (target) logChange('작업', target.title, 'delete', '', { snapshot: snapshotForRevert(target) })
    await persistAll()
  }

  async function addTaskLog(taskId, note, photos = []) {
    const task = state.value.tasks.find((item) => item.id === taskId)
    if (!task) {
      return
    }

    task.logs = task.logs || []
    task.logs.unshift({
      id: uuid(),
      date: new Date().toISOString(),
      note,
      photos: Array.isArray(photos) ? photos : [],
    })
    logChange('작업 진행기록', task.title, 'add', truncateForLog(note))

    await persistAll()
  }

  async function updateTaskLog(taskId, logId, patch) {
    const task = state.value.tasks.find((item) => item.id === taskId)
    if (!task || !Array.isArray(task.logs)) {
      return
    }

    const log = task.logs.find((item) => (item.id || item.date) === logId)
    if (!log) {
      return
    }

    const before = { ...log }
    if (patch.note !== undefined) {
      log.note = patch.note
    }
    if (patch.photos !== undefined) {
      log.photos = Array.isArray(patch.photos) ? patch.photos : []
    }

    const fields = diffFields(before, log, { note: '메모' })
    logChange('작업 진행기록', task.title, 'update', formatFieldDiff(fields), {
      refId: `${taskId}:${logId}`,
      fields,
    })

    await persistAll()
  }

  async function removeTaskLog(taskId, logId) {
    const task = state.value.tasks.find((item) => item.id === taskId)
    if (!task || !Array.isArray(task.logs)) {
      return
    }

    const target = task.logs.find((item) => (item.id || item.date) === logId)
    task.logs = task.logs.filter((item) => (item.id || item.date) !== logId)
    if (target) {
      logChange('작업 진행기록', task.title, 'delete', `메모: ${truncateForLog(target.note)}`, {
        refId: `${taskId}:${logId}`,
        snapshot: snapshotForRevert(target),
      })
    }
    await persistAll()
  }

  // 반복 규칙을 남겨두면 다음 실행 때 스케줄러가 작업을 다시 만들어 초기화가 무의미해진다.
  async function resetTasks() {
    const count = state.value.tasks.length
    state.value.tasks = []
    state.value.scheduleRules = []
    state.value.notifications = {}
    if (count > 0) logChange('작업', `전체 초기화 (${count}건)`, 'delete')
    await persistAll()
  }

  async function markTaskNotified(taskId, dateString) {
    state.value.notifications[taskId] = toKey(dateString)
    await persistAll()
  }

  function getTaskLastNotified(taskId) {
    return state.value.notifications[taskId]
  }

  async function createTaskFromTemplate(templateId) {
    const template = state.value.annualTaskTemplates.find((item) => item.id === templateId)
    if (!template) {
      return
    }

    const year = new Date().getFullYear()
    const dueDate = new Date(year, template.recommendedMonth - 1, 15)

    await upsertTask({
      title: template.title,
      dueDate: formatISO(dueDate, { representation: 'date' }),
      frequency: '매년',
      category: template.category ?? '연간 정기 작업',
      status: '예정',
      progress: 0,
      logs: [{ date: new Date().toISOString(), note: template.notes }],
    })
  }

  function listUpcomingDays(limit = 7) {
    const start = new Date()
    const end = addDays(start, limit)

    return state.value.tasks.filter((task) => {
      const due = parseISO(task.dueDate)
      return due >= start && due <= end && task.status !== '완료'
    })
  }

  return {
    upsertTask,
    removeTask,
    addTaskLog,
    updateTaskLog,
    removeTaskLog,
    resetTasks,
    markTaskNotified,
    getTaskLastNotified,
    createTaskFromTemplate,
    listUpcomingDays,
  }
}
