// 작업 CRUD + 진행기록 CRUD + 알림/템플릿/예정 목록 + 전체 초기화.
import { addDays, formatISO, parseISO } from 'date-fns'
import { uuid } from '../../utils/uuid.js'
import { diffFields, formatFieldDiff, snapshotForRevert, truncateForLog } from '../../utils/changeLogUtils.js'
import { toKey } from './scheduler.js'

export function createTaskActions(ctx) {
  const { state, persist, logChange } = ctx

  async function upsertTask(payload) {
    const index = state.value.tasks.findIndex((item) => item.id === payload.id)

    if (index >= 0) {
      const before = { ...state.value.tasks[index] }
      state.value.tasks[index] = {
        ...state.value.tasks[index],
        ...payload,
      }
      const fields = diffFields(before, state.value.tasks[index], {
        title: '제목',
        dueDate: '기한',
        frequency: '주기',
        category: '분류',
        priority: '우선순위',
        status: '상태',
        progress: '진행률',
        notes: '메모',
      })
      logChange('작업', state.value.tasks[index].title, 'update', formatFieldDiff(fields), { refId: payload.id, fields })
    } else {
      const dupKey = `${payload.title}|${payload.dueDate}`
      const alreadyExists = state.value.tasks.some(
        (t) => `${t.title}|${t.dueDate}` === dupKey,
      )
      if (!alreadyExists) {
        const created = {
          ...payload,
          id: payload.id || uuid(),
          logs: Array.isArray(payload.logs) ? payload.logs : [],
          checklist: Array.isArray(payload.checklist) ? payload.checklist : [],
          status: payload.status || '예정',
          progress: Number(payload.progress || 0),
          autoGenerated: payload.autoGenerated === true,
          scheduleRuleId: payload.scheduleRuleId || null,
        }
        state.value.tasks.push(created)
        logChange('작업', created.title, 'add')
      }
    }

    await persist('tasks')
  }

  async function removeTask(id) {
    const target = state.value.tasks.find((item) => item.id === id)
    state.value.tasks = state.value.tasks.filter((item) => item.id !== id)
    if (target) logChange('작업', target.title, 'delete', '', { snapshot: snapshotForRevert(target) })
    await persist('tasks')
  }

  async function addTaskLog(taskId, note, photos = []) {
    const task = state.value.tasks.find((item) => item.id === taskId)
    if (!task) {
      return
    }

    task.logs = task.logs || []
    task.logs.unshift({
      id: uuid(),
      date: new Date().toISOString(),
      note,
      photos: Array.isArray(photos) ? photos : [],
    })
    logChange('작업 진행기록', task.title, 'add', truncateForLog(note))

    await persist('tasks')
  }

  async function updateTaskLog(taskId, logId, patch) {
    const task = state.value.tasks.find((item) => item.id === taskId)
    if (!task || !Array.isArray(task.logs)) {
      return
    }

    const log = task.logs.find((item) => (item.id || item.date) === logId)
    if (!log) {
      return
    }

    const before = { ...log }
    if (patch.note !== undefined) {
      log.note = patch.note
    }
    if (patch.photos !== undefined) {
      log.photos = Array.isArray(patch.photos) ? patch.photos : []
    }

    const fields = diffFields(before, log, { note: '메모' })
    logChange('작업 진행기록', task.title, 'update', formatFieldDiff(fields), {
      refId: `${taskId}:${logId}`,
      fields,
    })

    await persist('tasks')
  }

  async function removeTaskLog(taskId, logId) {
    const task = state.value.tasks.find((item) => item.id === taskId)
    if (!task || !Array.isArray(task.logs)) {
      return
    }

    const target = task.logs.find((item) => (item.id || item.date) === logId)
    task.logs = task.logs.filter((item) => (item.id || item.date) !== logId)
    if (target) {
      logChange('작업 진행기록', task.title, 'delete', `메모: ${truncateForLog(target.note)}`, {
        refId: `${taskId}:${logId}`,
        snapshot: snapshotForRevert(target),
      })
    }
    await persist('tasks')
  }

  // ── 체크리스트(세부항목) ─────────────────────────────────────────────────────
  // 진행기록(logs)과 마찬가지로 작업 편집모드(showForm) 진입 없이 목록에서 바로
  // 추가·완료체크·삭제할 수 있는 하위 기록이다. 순서는 추가한 순서를 그대로 유지한다
  // (단계별 체크리스트라 위에서부터 순서대로 처리하는 경우가 많다 — 최신순으로 앞에
  // 끼워 넣는 진행기록과 다르게 unshift가 아니라 push한다).
  async function addChecklistItem(taskId, text) {
    const task = state.value.tasks.find((item) => item.id === taskId)
    if (!task || !text?.trim()) {
      return
    }

    task.checklist = task.checklist || []
    task.checklist.push({
      id: uuid(),
      text: text.trim(),
      done: false,
      doneAt: null,
    })
    logChange('작업 체크리스트', task.title, 'add', truncateForLog(text))

    await persist('tasks')
  }

  async function updateChecklistItem(taskId, itemId, patch) {
    const task = state.value.tasks.find((item) => item.id === taskId)
    if (!task || !Array.isArray(task.checklist)) {
      return
    }

    const item = task.checklist.find((entry) => entry.id === itemId)
    if (!item) {
      return
    }

    const before = { ...item }
    if (patch.text !== undefined) {
      item.text = patch.text
    }
    if (patch.done !== undefined) {
      item.done = !!patch.done
      item.doneAt = item.done ? new Date().toISOString() : null
    }

    const fields = diffFields(before, item, { text: '내용', done: '완료' })
    logChange('작업 체크리스트', task.title, 'update', formatFieldDiff(fields), {
      refId: `${taskId}:${itemId}`,
      fields,
    })

    await persist('tasks')
  }

  // 체크박스 클릭 한 번으로 완료/완료취소를 오간다(편집모드 진입 없이 바로 처리).
  async function toggleChecklistItem(taskId, itemId) {
    const task = state.value.tasks.find((item) => item.id === taskId)
    const item = task?.checklist?.find((entry) => entry.id === itemId)
    if (!item) {
      return
    }
    await updateChecklistItem(taskId, itemId, { done: !item.done })
  }

  // 순서변경은 다른 항목들의 순서 정보에 대해 이력을 남기면 클릭할 때마다 여러 줄이
  // 쌓여 이력이 순서변경으로 뒤덮이므로(다른 목록들의 순서변경도 이력을 남기지 않는다
  // — 예: reorderUsageGuideSteps), 여기서도 changeLog에 기록하지 않는다.
  async function reorderChecklistItems(taskId, newItems) {
    const task = state.value.tasks.find((item) => item.id === taskId)
    if (!task) {
      return
    }
    task.checklist = newItems
    await persist('tasks')
  }

  async function removeChecklistItem(taskId, itemId) {
    const task = state.value.tasks.find((item) => item.id === taskId)
    if (!task || !Array.isArray(task.checklist)) {
      return
    }

    const target = task.checklist.find((entry) => entry.id === itemId)
    task.checklist = task.checklist.filter((entry) => entry.id !== itemId)
    if (target) {
      logChange('작업 체크리스트', task.title, 'delete', `항목: ${truncateForLog(target.text)}`, {
        refId: `${taskId}:${itemId}`,
        snapshot: snapshotForRevert(target),
      })
    }
    await persist('tasks')
  }

  // 반복 규칙을 남겨두면 다음 실행 때 스케줄러가 작업을 다시 만들어 초기화가 무의미해진다.
  async function resetTasks() {
    const count = state.value.tasks.length
    state.value.tasks = []
    state.value.scheduleRules = []
    state.value.notifications = {}
    if (count > 0) logChange('작업', `전체 초기화 (${count}건)`, 'delete')
    await persist('tasks')
  }

  async function markTaskNotified(taskId, dateString) {
    state.value.notifications[taskId] = toKey(dateString)
    await persist('tasks')
  }

  function getTaskLastNotified(taskId) {
    return state.value.notifications[taskId]
  }

  async function createTaskFromTemplate(templateId) {
    const template = state.value.annualTaskTemplates.find((item) => item.id === templateId)
    if (!template) {
      return
    }

    const year = new Date().getFullYear()
    const dueDate = new Date(year, template.recommendedMonth - 1, 15)

    await upsertTask({
      title: template.title,
      dueDate: formatISO(dueDate, { representation: 'date' }),
      frequency: '매년',
      category: template.category ?? '연간 정기 작업',
      status: '예정',
      progress: 0,
      logs: [{ date: new Date().toISOString(), note: template.notes }],
    })
  }

  // ── 체크리스트 템플릿(사용자가 직접 만든, 반복해서 쓰는 작업 양식) ────────────────
  // annualTaskTemplates(계절 작업)와 달리 앱 고정 데이터가 아니라 농장에서 직접 만들고
  // 지우는 사용자 데이터라 다른 목록(작업·문제 등)과 같은 방식(전체 교체 upsert)으로 다룬다
  // — 체크리스트 항목 자체의 세부 편집(순서변경·이력 등)은 이 템플릿에는 두지 않는다
  // (실제 작업의 체크리스트만큼 자주 바뀌는 게 아니라 폼 하나로 통째로 다시 쓰는 편이 낫다).
  async function upsertChecklistTemplate(payload) {
    const checklist = (Array.isArray(payload.checklist) ? payload.checklist : [])
      .map((item) => ({ id: item.id || uuid(), text: item.text }))
      .filter((item) => item.text?.trim())

    const index = state.value.checklistTemplates.findIndex((item) => item.id === payload.id)
    if (index >= 0) {
      const before = { ...state.value.checklistTemplates[index] }
      state.value.checklistTemplates[index] = {
        ...state.value.checklistTemplates[index],
        title: payload.title,
        category: payload.category,
        priority: payload.priority,
        notes: payload.notes,
        checklist,
      }
      const fields = diffFields(before, state.value.checklistTemplates[index], {
        title: '제목',
        category: '분류',
        priority: '우선순위',
        notes: '메모',
      })
      logChange('작업 템플릿', state.value.checklistTemplates[index].title, 'update', formatFieldDiff(fields), {
        refId: payload.id,
        fields,
      })
    } else {
      const created = {
        id: payload.id || uuid(),
        title: payload.title,
        category: payload.category,
        priority: payload.priority || '보통',
        notes: payload.notes || '',
        checklist,
      }
      state.value.checklistTemplates.push(created)
      logChange('작업 템플릿', created.title, 'add')
    }

    await persist('tasks')
  }

  async function removeChecklistTemplate(id) {
    const target = state.value.checklistTemplates.find((item) => item.id === id)
    state.value.checklistTemplates = state.value.checklistTemplates.filter((item) => item.id !== id)
    if (target) {
      logChange('작업 템플릿', target.title, 'delete', '', { snapshot: snapshotForRevert(target) })
    }
    await persist('tasks')
  }

  // ── 체크리스트 템플릿 파일로 내보내기/불러오기(다른 농장과 공유) ────────────────
  // 사진이 없는 순수 데이터라 usageGuides의 exportUsageGuide/importUsageGuide처럼
  // 사진 id를 다시 저장하는 절차가 필요 없다 — 그만큼 훨씬 단순하다.
  const CHECKLIST_TEMPLATE_FILE_TYPE = 'citrus-checklist-template'

  function exportChecklistTemplate(id) {
    const template = state.value.checklistTemplates.find((item) => item.id === id)
    if (!template) {
      throw new Error('checklist-template-not-found')
    }

    return {
      type: CHECKLIST_TEMPLATE_FILE_TYPE,
      version: 1,
      exportedAt: new Date().toISOString(),
      template: {
        title: template.title,
        category: template.category,
        priority: template.priority,
        notes: template.notes || '',
        checklist: (template.checklist || []).map((item) => ({ text: item.text })),
      },
    }
  }

  function isValidChecklistTemplateFile(payload) {
    return Boolean(payload && payload.type === CHECKLIST_TEMPLATE_FILE_TYPE && payload.template && typeof payload.template === 'object')
  }

  // 다른 농장에서 내보낸 템플릿 파일을 이 농장에 새 템플릿으로 추가한다.
  async function importChecklistTemplate(payload) {
    if (!isValidChecklistTemplateFile(payload)) {
      throw new Error('invalid-checklist-template-file')
    }

    const { title, category, priority, notes, checklist } = payload.template
    await upsertChecklistTemplate({ title, category, priority, notes, checklist })
    return title
  }

  // 템플릿을 골라 날짜를 지정해 실제 작업으로 만든다 — 체크리스트 각 항목은 미완료 상태로
  // 복사된다(템플릿 자체의 항목과 id를 공유하지 않도록 새 id를 부여한다).
  async function createTaskFromChecklistTemplate(templateId, dueDate) {
    const template = state.value.checklistTemplates.find((item) => item.id === templateId)
    if (!template || !dueDate) {
      return
    }

    await upsertTask({
      title: template.title,
      dueDate,
      category: template.category,
      priority: template.priority || '보통',
      notes: template.notes || '',
      frequency: '1회',
      status: '예정',
      progress: 0,
      logs: [],
      checklist: (template.checklist || []).map((item) => ({
        id: uuid(),
        text: item.text,
        done: false,
        doneAt: null,
      })),
    })
  }

  function listUpcomingDays(limit = 7) {
    const start = new Date()
    const end = addDays(start, limit)

    return state.value.tasks.filter((task) => {
      const due = parseISO(task.dueDate)
      return due >= start && due <= end && task.status !== '완료'
    })
  }

  return {
    upsertTask,
    removeTask,
    addTaskLog,
    updateTaskLog,
    removeTaskLog,
    addChecklistItem,
    updateChecklistItem,
    toggleChecklistItem,
    reorderChecklistItems,
    removeChecklistItem,
    resetTasks,
    markTaskNotified,
    getTaskLastNotified,
    createTaskFromTemplate,
    upsertChecklistTemplate,
    removeChecklistTemplate,
    createTaskFromChecklistTemplate,
    exportChecklistTemplate,
    isValidChecklistTemplateFile,
    importChecklistTemplate,
    listUpcomingDays,
  }
}
